
const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY;

export const callGroqAPI = async (messages: any[]) => {
    if (GROQ_API_KEY) {
        try {
            const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${GROQ_API_KEY}`,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    messages: messages,
                    model: "llama3-70b-8192", // or appropriate model
                    temperature: 0.7,
                    response_format: { type: "json_object" }
                })
            });

            if (!response.ok) throw new Error("Groq API failed");
            const data = await response.json();
            const content = data.choices[0].message.content;
            return JSON.parse(content);
        } catch (e) {
            console.error("Real API call failed, falling back to mock", e);
        }
    }

    // Mock Response Logic
    const lastMsg = messages[messages.length - 1].content.toLowerCase();

    // 1. Concept Introduction
    if (lastMsg.includes("explain the concept")) {
        return {
            title: "Java Concept (Mock)",
            explanation: "This is a simulated explanation of the Java concept you asked for. In a real app with an API key, this would be generated by AI.",
            examples: ["public class Example { ... }", "int x = 5;"]
        };
    }

    // 2. Quiz Generation
    if (lastMsg.includes("generate 3 quiz questions") || lastMsg.includes("quiz")) {
        return {
            questions: [
                {
                    id: 1,
                    question: "What is the correct syntax for main method?",
                    options: ["public static void main(String[] args)", "void main()", "static public main", "none"],
                    correctAnswer: 0,
                    explanation: "Java entry point requires public static void main."
                },
                {
                    id: 2,
                    question: "Which data type is used for text?",
                    options: ["int", "char", "String", "boolean"],
                    correctAnswer: 2,
                    explanation: "String is used for text."
                },
                {
                    id: 3,
                    question: "How do you print to console?",
                    options: ["print()", "System.out.println()", "console.log()", "echo"],
                    correctAnswer: 1,
                    explanation: "System.out.println is standard Java output."
                }
            ]
        };
    }

    // 3. Logic Validation
    if (lastMsg.includes("validate this logic")) {
        return {
            is_correct: true,
            correct_approach: "Your approach seems valid for this problem.",
            feedback: "Good mock logic! Proceed to coding."
        };
    }

    // 4. Code Evaluation
    if (lastMsg.includes("evaluate this java code")) {
        return {
            status: "success",
            feedback: "Great job! This mock code evaluation passed."
        };
    }

    // 5. Questions
    if (lastMsg.includes("answer as a supportive")) {
        return {
            answer: "This is a mock answer to your question. Keep up the good work!"
        };
    }

    // 6. Deep Analysis / General (Fallback)
    return {
        status: "OPTIMAL",
        message: "Code looks good!",
        summary: "No issues found (Mock)",
        explanation: "This is a fallback mock response.",
        root_cause: [],
        corrected_code: null
    };
};
